# Generated by Django 3.0.2 on 2020-03-10 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.CharField(default=datetime.date(2020, 3, 11), max_length=32),
        ),
        migrations.DeleteModel(
            name='BookingKayaks',
        ),
        migrations.DeleteModel(
            name='Term',
        ),
    ]
