# Generated by Django 3.0.5 on 2020-04-16 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_auto_20200415_1500'),
    ]

    operations = [
        migrations.RunSQL("UPDATE SQLITE_SEQUENCE SET SEQ=500 WHERE NAME='app2_bookingdate';")
    ]
