# Generated by Django 3.0.2 on 2020-03-17 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0008_auto_20200317_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.CharField(default=datetime.date(2020, 3, 17), max_length=32),
        ),
    ]
