# Generated by Django 3.0.2 on 2020-03-17 10:45

import app2.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0009_auto_20200317_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.CharField(default=app2.models.get_date, max_length=32),
        ),
    ]
