# Generated by Django 3.0.2 on 2020-03-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0013_auto_20200319_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.CharField(max_length=32),
        ),
    ]
