# Generated by Django 3.0.2 on 2020-03-19 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0015_auto_20200319_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.date(2020, 3, 19)),
        ),
    ]
