# Generated by Django 3.0.2 on 2020-03-21 09:21

import app2.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0016_auto_20200319_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.ForeignKey(default='', limit_choices_to=app2.models.booking_dates_limit, on_delete=django.db.models.deletion.CASCADE, to='app2.BookingDate'),
        ),
    ]
