# Generated by Django 3.0.2 on 2020-04-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0018_auto_20200331_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
    ]
