# Generated by Django 3.0.5 on 2020-04-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='average_time',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='main_points',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='next_stage',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='stop_place',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
