# Generated by Django 3.0.5 on 2020-04-15 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingdate',
            old_name='booking_date',
            new_name='date',
        ),
    ]
