# Generated by Django 3.0.5 on 2020-04-07 08:15

import client_panel.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DateList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TermKayaks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.RenameField(
            model_name='kayak',
            old_name='quantity',
            new_name='stock',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='kayak',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='term',
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kayak',
            name='store',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(choices=[('', 'Kliknij'), ('9:00', '9:00'), ('9:30', '9:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00')], default='', max_length=32),
        ),
        migrations.DeleteModel(
            name='BookingKayaks',
        ),
        migrations.AddField(
            model_name='termkayaks',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_bookings', to='client_panel.Booking'),
        ),
        migrations.AddField(
            model_name='termkayaks',
            name='kayak',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kayaks', to='client_panel.Kayak'),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.ForeignKey(default='', limit_choices_to=client_panel.models.booking_dates_limit, on_delete=django.db.models.deletion.CASCADE, to='client_panel.BookingDate'),
        ),
    ]
