# Generated by Django 3.0.5 on 2020-04-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0002_auto_20200418_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='kayak',
            name='dimenstions',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kayak',
            name='displacement',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kayak',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='kayak',
            name='prize',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kayak',
            name='weight',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
