# Generated by Django 3.0.2 on 2020-02-28 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0002_remove_booking_kayak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingkayaks',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_set', to='client_panel.Booking'),
        ),
        migrations.AlterField(
            model_name='bookingkayaks',
            name='kayak',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_kayaks', to='client_panel.Kayak'),
        ),
    ]
