# Generated by Django 3.0.5 on 2020-04-15 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0002_auto_20200415_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingdate',
            old_name='date',
            new_name='booking_date',
        ),
    ]
