# Generated by Django 3.0.5 on 2020-04-15 13:00

import client_panel.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0003_auto_20200415_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.ForeignKey(default='', limit_choices_to=client_panel.models.booking_dates_limit, on_delete=django.db.models.deletion.CASCADE, related_name='cp_booking_date', to='client_panel.BookingDate'),
        ),
    ]
