# Generated by Django 3.0.2 on 2020-02-29 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0004_auto_20200228_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingkayaks',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='client_panel.Booking'),
        ),
        migrations.AlterField(
            model_name='bookingkayaks',
            name='kayak',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kayaks', to='client_panel.Kayak'),
        ),
    ]
