# Generated by Django 3.0.5 on 2020-04-16 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0004_auto_20200415_1500'),
    ]

    operations = [
        migrations.RunSQL("UPDATE SQLITE_SEQUENCE SET SEQ=1000 WHERE NAME='client_panel_bookingdate';")
    ]
