# Generated by Django 3.0.5 on 2020-04-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0005_auto_20200420_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kayak',
            name='type',
            field=models.CharField(choices=[('Jednosoboy', 'Jednoosobowy'), ('Dwuosobowy', 'Dwuosobowy'), ('Trzyosobowy', 'Trzyosobowy')], max_length=32),
        ),
    ]
