# Generated by Django 3.0.2 on 2020-03-02 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0006_auto_20200302_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(choices=[(0, '02-03-2020'), (1, '03-03-2020'), (2, '04-03-2020'), (3, '05-03-2020'), (4, '06-03-2020'), (5, '07-03-2020'), (6, '08-03-2020')], max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='bookingkayaks',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_panel.Term'),
        ),
    ]
