# Generated by Django 3.0.2 on 2020-03-02 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0008_auto_20200302_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term',
            old_name='data',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='term2',
        ),
    ]
