# Generated by Django 3.0.5 on 2020-04-28 06:15

import client_panel.code_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0008_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='code',
            field=models.CharField(default=client_panel.code_generator.random_string, max_length=32),
        ),
    ]
