# Generated by Django 3.0.2 on 2020-03-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0010_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='date',
            field=models.DateField(),
        ),
    ]
