# Generated by Django 3.0.2 on 2020-03-02 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0011_auto_20200302_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='term',
        ),
    ]
