# Generated by Django 3.0.5 on 2020-05-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0013_auto_20200506_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
