# Generated by Django 3.0.2 on 2020-03-04 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0014_auto_20200303_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='boat',
        ),
        migrations.RemoveField(
            model_name='term',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='term',
            name='object_id',
        ),
    ]
