# Generated by Django 3.0.2 on 2020-03-04 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0016_auto_20200304_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingkayaks',
            name='date',
        ),
        migrations.RemoveField(
            model_name='bookingkayaks',
            name='kayak',
        ),
        migrations.RemoveField(
            model_name='bookingkayaks',
            name='quantity',
        ),
        migrations.CreateModel(
            name='TermKayaks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='client_panel.Term')),
                ('kayak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kayaks', to='client_panel.Kayak')),
            ],
        ),
        migrations.AddField(
            model_name='bookingkayaks',
            name='term_kayaks',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client_panel.TermKayaks'),
            preserve_default=False,
        ),
    ]
