# Generated by Django 3.0.2 on 2020-03-04 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0017_auto_20200304_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingkayaks',
            old_name='term_kayaks',
            new_name='date_kayaks',
        ),
    ]
