# Generated by Django 3.0.2 on 2020-03-04 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0019_termkayaks_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termkayaks',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_bookings', to='client_panel.Booking'),
        ),
    ]
