# Generated by Django 3.0.2 on 2020-03-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0021_auto_20200304_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='kayak',
            name='available_amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
