# Generated by Django 3.0.2 on 2020-03-05 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0023_term_daily_kayaks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kayak',
            name='available_amount',
        ),
    ]
