# Generated by Django 3.0.2 on 2020-03-05 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0025_auto_20200305_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingkayaks',
            name='daily_kayaks',
            field=models.ForeignKey(default=[0], on_delete=django.db.models.deletion.CASCADE, related_name='daily_kayaks', to='client_panel.Kayak'),
        ),
        migrations.CreateModel(
            name='DailyKayak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finder', models.IntegerField()),
                ('eoli', models.IntegerField()),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term', to='client_panel.Term')),
            ],
        ),
    ]
