# Generated by Django 3.0.2 on 2020-03-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0026_auto_20200305_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailykayak',
            name='protour',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
