# Generated by Django 3.0.2 on 2020-03-05 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0028_dailykayakbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailykayakbooking',
            name='quantity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity', to='client_panel.DailyKayak'),
        ),
    ]
