# Generated by Django 3.0.2 on 2020-03-05 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0029_auto_20200305_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailykayakbooking',
            name='amount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='amount', to='client_panel.DailyKayak'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailykayakbooking',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
