# Generated by Django 3.0.2 on 2020-03-06 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0030_auto_20200305_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailykayakbooking',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='dailykayakbooking',
            name='booking',
        ),
        migrations.DeleteModel(
            name='DailyKayak',
        ),
        migrations.DeleteModel(
            name='DailyKayakBooking',
        ),
    ]
