# Generated by Django 3.0.2 on 2020-03-06 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0031_auto_20200306_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingkayaks',
            name='daily_kayaks',
        ),
    ]
