# Generated by Django 3.0.2 on 2020-03-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0033_auto_20200309_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
