# Generated by Django 3.0.2 on 2020-03-09 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0034_auto_20200309_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
