# Generated by Django 3.0.2 on 2020-03-10 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0035_auto_20200309_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='date',
            field=models.DateField(default=datetime.date(2020, 3, 10)),
        ),
    ]
