# Generated by Django 3.0.2 on 2020-03-10 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0036_auto_20200310_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingkayaks',
            name='date',
            field=models.ForeignKey(default='ASD', on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='client_panel.Term'),
        ),
    ]
