# Generated by Django 3.0.2 on 2020-03-10 12:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0037_auto_20200310_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingkayaks',
            name='date',
            field=models.ForeignKey(default=datetime.date.today, on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='client_panel.Term'),
        ),
        migrations.AlterField(
            model_name='term',
            name='date',
            field=models.DateField(),
        ),
    ]
