# Generated by Django 3.0.2 on 2020-03-10 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0038_auto_20200310_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingkayaks',
            name='date',
            field=models.TextField(default=datetime.date.today),
        ),
        migrations.DeleteModel(
            name='Term',
        ),
    ]
