# Generated by Django 3.0.2 on 2020-03-10 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0039_auto_20200310_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingkayaks',
            name='date',
            field=models.CharField(default=datetime.date.today, max_length=32),
        ),
    ]
