# Generated by Django 3.0.2 on 2020-03-10 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0040_auto_20200310_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.CharField(default=datetime.date.today, max_length=32),
        ),
        migrations.DeleteModel(
            name='BookingKayaks',
        ),
    ]
