# Generated by Django 3.0.2 on 2020-03-13 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0043_auto_20200311_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.CharField(default=datetime.date(2020, 3, 14), max_length=32),
        ),
    ]
