# Generated by Django 3.0.2 on 2020-03-16 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0045_kayak_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.CharField(default=datetime.date(2020, 3, 16), max_length=32),
        ),
    ]
