# Generated by Django 3.0.2 on 2020-03-16 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0046_auto_20200316_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.CharField(default=datetime.date(2020, 3, 18), max_length=32),
        ),
    ]
