# Generated by Django 3.0.2 on 2020-03-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0047_auto_20200316_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
