# Generated by Django 3.0.2 on 2020-03-17 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0048_auto_20200317_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.CharField(default=datetime.date(2020, 3, 18), max_length=32),
        ),
    ]
