# Generated by Django 3.0.2 on 2020-03-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0049_auto_20200317_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(),
        ),
    ]
