# Generated by Django 3.0.2 on 2020-03-18 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0051_auto_20200318_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=datetime.date(2020, 3, 19)),
        ),
    ]
