# Generated by Django 3.0.2 on 2020-03-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0053_auto_20200318_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
