# Generated by Django 3.0.2 on 2020-03-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0054_auto_20200318_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(),
        ),
    ]
