# Generated by Django 3.0.2 on 2020-03-20 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0056_auto_20200319_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.CharField(default=datetime.date(2020, 3, 22), max_length=32),
        ),
    ]
