# Generated by Django 3.0.2 on 2020-03-20 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0057_auto_20200320_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client_panel.DateList'),
        ),
    ]
