# Generated by Django 3.0.2 on 2020-03-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0059_auto_20200320_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datelist',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
