# Generated by Django 3.0.2 on 2020-03-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0060_auto_20200320_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datelist',
            name='date',
            field=models.DateField(),
        ),
    ]
