# Generated by Django 3.0.2 on 2020-03-20 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0063_booking_booking_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingdate',
            old_name='date',
            new_name='booking_date',
        ),
    ]
