# Generated by Django 3.0.2 on 2020-03-20 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0064_auto_20200320_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
    ]
