# Generated by Django 3.0.2 on 2020-03-20 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0065_remove_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='client_panel.BookingDate'),
        ),
    ]
