# Generated by Django 3.0.2 on 2020-03-20 13:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0066_auto_20200320_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.ForeignKey(default=datetime.date(2020, 3, 20), on_delete=django.db.models.deletion.CASCADE, to='client_panel.BookingDate'),
        ),
    ]
