# Generated by Django 3.0.2 on 2020-03-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_panel', '0071_auto_20200320_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termkayaks',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
