# Generated by Django 3.0.5 on 2020-04-28 06:24

import app1.code_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='code',
            field=models.CharField(default=app1.code_generator.random_string, max_length=32),
        ),
    ]
