# Generated by Django 3.0.5 on 2020-04-16 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("ALTER SEQUENCE app2_bookingdate_id_seq START with 500 RESTART;"),
    ]
