# Generated by Django 3.0.5 on 2020-04-16 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("UPDATE SQLITE_SEQUENCE SET SEQ=500 WHERE NAME='app2_bookingdate';"),
        migrations.RunSQL("UPDATE SQLITE_SEQUENCE SET SEQ=1000 WHERE NAME='client_panel_bookingdate';")
    ]
