# Generated by Django 3.0.5 on 2020-04-07 08:15

import app1.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Kayak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('stock', models.IntegerField()),
                ('store', models.IntegerField()),
                ('type', models.CharField(choices=[('Jednosoboy', 'Jednoosobwy'), ('Dwuosobowy', 'Dwuosobowy'), ('Trzyosobowy', 'Trzyosobowy')], max_length=32)),
                ('available', models.BooleanField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TermKayaks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Term',
            new_name='BookingDate',
        ),
        migrations.RemoveField(
            model_name='dailykayakbooking',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='dailykayakbooking',
            name='booking',
        ),
        migrations.RenameField(
            model_name='bookingdate',
            old_name='date',
            new_name='booking_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.ForeignKey(default='', limit_choices_to=app1.models.booking_dates_limit, on_delete=django.db.models.deletion.CASCADE, to='app1.BookingDate'),
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(choices=[('', 'Kliknij'), ('9:00', '9:00'), ('9:30', '9:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00')], default='', max_length=32),
        ),
        migrations.DeleteModel(
            name='DailyKayak',
        ),
        migrations.DeleteModel(
            name='DailyKayakBooking',
        ),
        migrations.AddField(
            model_name='termkayaks',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app1_term_bookings', to='app1.Booking'),
        ),
        migrations.AddField(
            model_name='termkayaks',
            name='kayak',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app1_kayaks', to='app1.Kayak'),
        ),
    ]
