# Generated by Django 3.0.5 on 2020-04-15 13:00

import app1.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.ForeignKey(default='', limit_choices_to=app1.models.booking_dates_limit, on_delete=django.db.models.deletion.CASCADE, related_name='app1_booking_date', to='app1.BookingDate'),
        ),
    ]
