# Generated by Django 3.0.2 on 2020-03-24 11:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200322_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='exact_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
