# Generated by Django 3.0.5 on 2020-04-17 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_create_custom_index'),
    ]

    operations = [
        migrations.RunSQL("ALTER SEQUENCE app2_bookingdate_id_seq START with 500 RESTART;"),
        migrations.RunSQL("ALTER SEQUENCE client_panel_bookingdate_id_seq START with 1000 RESTART;"),
    ]
