# Generated by Django 3.0.5 on 2020-05-05 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200429_1405'),
    ]

    operations = [
        migrations.RunSQL("ALTER SEQUENCE app1_booking_id_seq START with 1 RESTART;"),
        migrations.RunSQL("ALTER SEQUENCE app2_booking_id_seq START with 2000 RESTART;"),
        migrations.RunSQL("ALTER SEQUENCE client_panel_booking_id_seq START with 4000 RESTART;"),
    ]
