# Generated by Django 3.0.2 on 2020-03-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_booking_exact_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='exact_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
