# Generated by Django 3.0.5 on 2020-05-05 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200429_1405'),
    ]

    operations = [
        migrations.RunSQL("UPDATE SQLITE_SEQUENCE SET SEQ=1 WHERE NAME='app1_booking';"),
        migrations.RunSQL("UPDATE SQLITE_SEQUENCE SET SEQ=1000 WHERE NAME='app2_booking';"),
        migrations.RunSQL("UPDATE SQLITE_SEQUENCE SET SEQ=2000 WHERE NAME='client_panel_booking';")
    ]
