# Generated by Django 3.0.2 on 2020-03-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20200324_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termkayaks',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
