# Generated by Django 3.0.2 on 2020-03-31 11:23

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20200330_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=phone_field.models.PhoneField(default=1, max_length=31),
            preserve_default=False,
        ),
    ]
