# Generated by Django 3.0.2 on 2020-03-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_booking_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
