# Generated by Django 3.0.2 on 2020-04-02 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0014_booking_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='termkayaks',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='termkatays_app1', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
