# Generated by Django 3.0.2 on 2020-04-02 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_termkayaks_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termkayaks',
            name='user',
        ),
    ]
